[project]
name = "pymol"
readme = "README.md"
requires-python = ">=3.9"
dynamic=["version"]
license = {file = "LICENSE"}
description = "PyMOL is a Python-enhanced molecular graphics tool for 3D molecular visualization."
authors = [
  {name = "Schrodinger", email = "pymol-users@lists.sourceforge.net"},
]
dependencies = [
  "numpy>=2.0",
  "PySide6>=6.0",
]

[build-system]
build-backend = "scikit_build_core.build"
requires = [
  "numpy>=2.0",
  "pathspec==0.12.0",
  "scikit-build-core>=0.12.2",
]

[project.optional-dependencies]
dev = [
  "biopython>=1.80",
  "msgpack==1.0.8",
  "pillow==11.1.0",
  "PySide6==6.8.1",
  "pytest==8.2.2",
  "requests==2.32.3",
]

[project.urls]
Homepage = "https://pymol.org"
Documentation = "https://pymol.org/dokuwiki"
Repository = "https://github.com/schrodinger/pymol-open-source"
"Bug Tracker" = "https://github.com/schrodinger/pymol-open-source/issues"
Changelog = "https://github.com/schrodinger/pymol-open-source/blob/master/ChangeLog"

[project.scripts]
pymol = "pymol:launch"
[tool.scikit-build]
minimum-version = "build-system.requires"
wheel.packages = [
  "modules/pymol",
  "modules/pymol2",
  "modules/pmg_qt",
  "modules/pmg_tk",
  "modules/chempy",
  "modules/web",
]

[tool.scikit-build.metadata.version]
provider = "scikit_build_core.metadata.regex"
input = "layer0/Version.h"
regex = '#define\s+_PyMOL_VERSION\s+"(?P<value>[^"]+)"'

